from(bucket: "redstone")
  |> range(start: -1m)
  |> filter(fn: (r) => r["_measurement"] == "dataPackages")
  |> keep(columns: ["dataServiceId"])
  |> group()
  |> distinct(column: "dataServiceId")
  |> yield(name: "dataServiceId")
