name: Find New Sources

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  find-new-sources:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Install ts-node
      run: npm install -g ts-node

    - name: Run find-new-sources-ts.ts
      run: ts-node find-new-sources-ts.ts
